# Build using: docker build -f Dockerfile.gocd-agent -t gocd-agent .
FROM phusion/baseimage:0.9.16
MAINTAINER Aravind SV <arvind.sv@gmail.com>

RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN apt-get update && apt-get install -y -q unzip openjdk-7-jre-headless git vim

# Download the docker binary
ENV DOCKER_VERSION=1.6.2
RUN wget https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION} && \
    chmod +x docker-${DOCKER_VERSION} && \
    mv docker-${DOCKER_VERSION} /usr/local/bin/docker

RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

RUN mkdir /etc/service/go-agent
ADD gocd-agent/go-agent-start.sh /etc/service/go-agent/run

ADD http://download.go.cd/gocd-deb/go-agent-15.1.0-1863.deb /tmp/go-agent.deb

WORKDIR /tmp
RUN dpkg -i /tmp/go-agent.deb
RUN sed -i 's/DAEMON=Y/DAEMON=N/' /etc/default/go-agent

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

CMD ["/usr/share/go-agent/agent.sh"]
